language: python
python: 3.7
cache: pip
install: pip install -r requirements.txt
env:
    - TEST_FILE=test_view.py
    - TEST_FILE=test_model.py
    - TEST_FILE=test_controller.py
before_script:
    - echo 'export DISPLAY=:0.0' >> ~/.bashrc
script:
    - python -m pytest test/$TEST_FILE -vv
