language: python
os:
    - linux
    # - osx
    - windows
python: 3.7
cache: pip
install: pip install -r requirements.txt
script:
    - python -m pytest test/test_view.py -vv
    - python -m pytest test/test_model.py -vv
    - python -m pytest test/test_controller.py -vv
